name: Sync to Pinata IPFS

on:
  push:
    paths:
      - 'text.txt'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Upload to Pinata
          env:
            PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
            PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
          run: |
            curl -X POST https://api.pinata.cloud/pinning/pinFileToIPFS \
            -H "pinata_api_key: $PINATA_API_KEY" \
            -H "pinata_secret_api_key: $PINATA_API_SECRET" \
            -F file=@text.txt
